export const Agents = [
    {
        id: 1,
        name: 'Writing Assistant',
        desc: 'Write , rewrite, and fix texts quickly and easily.',
        image: require('../assets/images/agent_1.png'),
        initialText: 'Write an email requesting leave from my manager for next Monday.',
        prompt: 'You are a writing assistant. Help users write, rewrite, summarize, and fix texts quickly and easily.',
        type: 'chat',
        featured: true,
    },
    {
        id: 2,
        name: 'Image Generator',
        desc: 'Generate images based on text descriptions.',
        image: require('../assets/images/agent_2.png'),
        initialText: 'A futuristic cityscape at sunset, with flying cars and towering skyscrapers.',
        prompt: 'You are an AI image Generator. Generate images based on text descriptions provided by users.',
        type: 'image',
        featured: true,
    },
    {
        id: 3,
        name: 'Translation',
        desc: 'Translate text accurately between multiple languages.',
        image: require('../assets/images/agent_3.png'),
        initialText: 'Translate "Hello, how are you?" to Tamil.',
        prompt: 'You are a translation expert. Translate texts with high accuracy between multiple languages.',
        type: 'translation',
        featured: true,
    },
    {
        id: 4,
        name: 'Progress Coach',
        desc: 'Plan tasks, set goals, and manage time effectively.',
        image: require('../assets/images/productivity_coach.json'),
        initialText: 'Create a daily to-do list for preparing for SDE-1 reactNative interview.',
        prompt: 'You are a productivity expert. Help users plan tasks, set goals, and manage time effectively.',
        type: 'chat',
        featured: false,
    },
    {
        id: 5,
        name: 'Fitness Trainer',
        desc: 'Design personalized workout routines and provide fitness advice.',
        image: require('../assets/images/fitness_coach.json'),
        initialText: 'Create a diet plan for lean muscle gain with high protein intake.',
        prompt: 'You are a fitness expert. Design personalized workout routines and provide fitness advice.',
        type: 'chat',
        featured: false,
    },
    {
        id: 6,
        name: 'Math Solver',
        desc: 'Solve complex math problems and explain solutions step-by-step.',
        image: require('../assets/images/math_solver.json'),
        initialText: 'Solve the equation 2x + 3 = 7 and explain the steps.',
        prompt: 'You are a math expert. Solve complex math problems and explain solutions step-by-step.',
        type: 'chat',
        featured: false,
    },
    {
        id: 7,
        name: 'Tech Update',
        desc: 'Stay updated with the latest technology news and trends.',
        image: require('../assets/images/Tech_update.json'),
        initialText: 'What are the latest advancements in the field of software development?',
        prompt: 'You are a tech expert. Provide users with the latest technology news and trends.',
        type: 'chat',
        featured: false,
    },
    // {
    //         id: 8,
    //         name: 'Grammar Fixer',
    //         desc: 'Fix grammar and spelling errors.',
    //         image: require('../assets/images/agent_4.png'),
    //         initialText: 'I going to office yesterday.',
    //         prompt: 'You are a grammar assistant. Correct grammar and spelling without changing meaning.',
    //         type: 'chat',
    //         featured: false
    //     },
    //     {
    //         id: 9,
    //         name: 'Fitness Coach',
    //         desc: 'Get workouts and diet tips.',
    //         image: require('../assets/images/agent_1.png'),
    //         initialText: 'Create a 4-day workout plan for weight loss.',
    //         prompt: 'You are a fitness assistant. Suggest workouts and meal plans.',
    //         type: 'chat',
    //         featured: false
    //     },
    //     {
    //         id: 10,
    //         name: 'Code Assistant',
    //         desc: 'Write and debug code.',
    //         image: require('../assets/images/agent_2.png'),
    //         initialText: 'Write a Python function to check if a number is prime.',
    //         prompt: 'You are a coding assistant. Generate and explain code.',
    //         type: 'chat',
    //         featured: false
    //     },
    //     {
    //         id: 11,
    //         name: 'Research Assistant',
    //         desc: 'Summarize and organize information.',
    //         image: require('../assets/images/agent_3.png'),
    //         initialText: 'Summarize key points from an article about climate change.',
    //         prompt: 'You are a research assistant. Summarize and simplify information.',
    //         type: 'chat',
    //         featured: false
    //     },
    //     {
    //         id: 12,
    //         name: 'Storyteller',
    //         desc: 'Create stories or poems.',
    //         image: require('../assets/images/agent_4.png'),
    //         initialText: 'Tell a short bedtime story about a dragon and a princess.',
    //         prompt: 'You are a storyteller. Write imaginative stories for kids and adults.',
    //         type: 'chat',
    //         featured: false
    //     },
    //     {
    //         id: 13,
    //         name: 'Email Generator',
    //         desc: 'Draft professional emails.',
    //         image: require('../assets/images/agent_1.png'),
    //         initialText: 'Write a professional email to a client about project updates.',
    //         prompt: 'You are an email assistant. Write clear, concise emails.',
    //         type: 'chat',
    //         featured: false
    //     },
    {
        id: 14,
        name: 'Caption Generator',
        desc: 'Create captions for social media.',
        image: require('../assets/images/agent_4.png'),
        initialText: 'A picture of a puppy playing in the park.',
        prompt: 'You are a caption generator. Create short, catchy captions with hashtags.',
        type: 'image+text',
        featured: true
    },
];